services:
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    container_name: cme_mongodb
    volumes:
      - db-volume:/data/db
      - configdb-volume:/data/configdb
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - "MONGO_INITDB_ROOT_USERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD"
      - "MONGO_INITDB_DATABASE=admin"
      - "CME_DB_USERNAME"
      - "CME_DB_PASSWORD"
      - "CME_DB_NAME"
volumes:
  db-volume: {}
  configdb-volume: {}
