services:
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    container_name: cme_mongodb
    volumes:
      - db-volume:/data/db
      - configdb-volume:/data/configdb
    networks:
      - internal
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
volumes:
  db-volume: {}
  configdb-volume: {}
networks:
  internal: {}
    internal: true
