services:
  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    container_name: cme_mongodb
    volumes:
      - db-volume:/data/db
      - configdb-volume:/data/configdb
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - "MONGO_INITDB_ROOT_USERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD"
      - "MONGO_INITDB_DATABASE=admin"
      - "CME_DB_USERNAME"
      - "CME_DB_PASSWORD"
      - "CME_DB_NAME"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports:
      - "8081:8081"
volumes:
  db-volume: {}
  configdb-volume: {}
