version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    container_name: "cme_api"
    environment:
      - "LANDSCAPE"
      - "CME_DB_USERNAME"
      - "CME_DB_PASSWORD"
      - "CME_DB_NAME"
      - "CME_DB_ADDRESS"
      - "CRAWLER_DB_USERNAME"
      - "CRAWLER_DB_PASSWORD"
      - "CRAWLER_DB_NAME"
      - "CRAWLER_DB_ADDRESS"
      - "CME_ADMIN_PASSWORD"
      - "SENTIMENT_CLIENT_PASSWORD"
      - "CRAWLER_CLIENT_PASSWORD"
    volumes:
      - ./resources/plenarprotokolle/open_data:/plenarprotokolle/
    ports:
      - "127.0.0.1:9002:9001"
  mongodb:
    image: mongo:latest
    networks:
      - internal
    expose:
      - "27017"
    container_name: cme_mongodb
    volumes:
      - db-volume:/data/db
      - configdb-volume:/data/configdb
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      - "MONGO_INITDB_ROOT_USERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD"
      - "MONGO_INITDB_DATABASE=admin"
      - "CME_DB_USERNAME"
      - "CME_DB_PASSWORD"
      - "CME_DB_NAME"
volumes:
  db-volume: { }
  configdb-volume: { }
networks:
  internal: { }